#ifndef _BFP_DEFINES_H_
#define _BFP_DEFINES_H_

enum BFP_FILE_TYPE { BFP_TEXT_FILE = 1, BFP_BINARY_FILE };

enum BFP_ENDIAN_TYPE {
    BFP_ENDIAN_UNKNOWN = 0, BFP_ENDIAN_LITTLE,
    BFP_ENDIAN_BIG, BFP_ENDIAN_MIDDLE
};

typedef float scalar;
#define PI_CONST  3.14159265358979323846
#define BFP_NULL_FLOAT   1.0E20f
#define DEG_TO_RAD(angle)  (angle * PI_CONST / 180)
#define RAD_TO_DEG(radian) (radian * 180 / PI_CONST)

enum BFP_COORDINATE_TYPE { BFP_LEFT_HANDED = 1, BFP_RIGHT_HANDED };

enum BFP_PLANE_STATUS {
    BFP_PLANE_FRONT = 1, BFP_PLANE_BACK, BFP_PLANE_ON_PLANE,
    BFP_PLANE_CLIPPED, BFP_PLANE_CULLED, BFP_PLANE_VISIBLE
};

#define BFP_MIN(a, b) (a < b ? a : b)
#define SIGN(a) (a < 0.0f) ? -1.0f : 1.0f
#define BFP_MAX_CLIPPING_VERTS 64

#define BFP_NULL_HANDLE  -1

enum BRESULT {
    BFP_FAIL = 0, BFP_SUCCESS, BFP_VERTEX_SHADER_FAIL,
    BFP_PIXEL_SHADER_FAIL, BFP_SHADER_FAIL,
    BFP_PARAMETERS_FAIL, BFP_DEVICE_FAIL
};

typedef char BSTATE;
#define BFP_TRUE   1
#define BFP_FALSE  0

enum BFP_NETWORK_MESSAGE_TYPE {
    BFP_MESSAGE_SERVER_DISCONNECT = 0,
    BFP_MESSAGE_CLIENT_DISCONNECT,
    BFP_MESSAGE_FORCE_DISCONNECT,
    BFP_MESSAGE_CONNECT_ACCEPTED,
    BFP_MESSAGE_SEND_ERROR,
    BFP_MESSAGE_RESPOND_REQUIRE,
    BFP_MESSAGE_RESPOND_OK
};

enum BFP_NETWORK_TYPE {
    BFP_NETWORK_NULL = 0,
    BFP_NETWORK_SERVER,
    BFP_NETWORK_CLIENT
};

enum BNETWORKRESULT {
    BFP_NO_DATA = 0,
    BFP_DATA_FAIL,
    BFP_PARTIAL_DATA,
    BFP_DATA_SUCCESS
};

typedef char BPACKETVALUE;

#define BFP_MAX_PACKET_SIZE 256
#define BFP_NETWORK_CALLBACK(a) void(*a)(int u, int t, char *d, int s)
#define BFP_NETWORK_SYSTEM_USAGE 0

enum BFP_RENDER_STATE {
    BFP_DEPTH_TESTING = 1,
    BFP_SMOOTH_SHADING,
    BFP_TEXTURE_2D,
    BFP_TEXTURE_CUBE,
    BFP_ALPHA_TESTING,
    BFP_BACK_CCW_CULLING,
    BFP_BACK_CW_CULLING,
    BFP_FRONT_CCW_CULLING,
    BFP_FRONT_CW_CULLING,
    BFP_TOTAL_RENDER_STATES
};

enum BFP_ALPHA_STATE {
    BFP_ALPHA_LESS = 1,
    BFP_ALPHA_GREATER
};

enum BFP_FILTER_TYPE {
    BFP_NO_FILTER = 0,
    BFP_MIN_POINT_FILTER,
    BFP_MAG_POINT_FILTER,
    BFP_MIP_POINT_FILTER,
    BFP_MIN_LINEAR_FILTER,
    BFP_MAG_LINEAR_FILTER,
    BFP_MIP_LINEAR_FILTER,
    BFP_USE_ANSIO_FILTER,
    BFP_S_REPEAT_FILTER,
    BFP_T_REPEAT_FILTER,
    BFP_R_REPEAT_FILTER,
    BFP_S_CLAMP_FILTER,
    BFP_T_CLAMP_FILTER,
    BFP_R_CLAMP_FILTER,
    BFP_S_EDGE_CLAMP_FILTER,
    BFP_T_EDGE_CLAMP_FILTER,
    BFP_R_EDGE_CLAMP_FILTER
};

enum BFP_TEXTURE_TYPE {
    BFP_TEX2D_TYPE = 1,
    BFP_CUBE_TYPE
};

enum BFP_TEXTURE_FORMAT {
    BFP_TEX_UNSIGNED_BYTE = 1,
    BFP_TEX_FLOAT
};

#define BFP_MAX_TEXTURES 16

enum BFP_MATRIX_TYPE {
    BFP_PROJECTION_MATRIX = 1,
    BFP_MODELVIEW_MATRIX,
    BFP_TEXTURE_MATRIX,
    BFP_MVP_MATRIX
};

enum BFP_MATRIX_FORMAT {
    BFP_IDENTITY_MATRIX = 1,
    BFP_TRANSPOSE_MATRIX,
    BFP_INVERSE_MATRIX,
    BFP_INVERSE_TRANSPOSE_MATRIX
};

enum BFP_PROJECTION_TYPE {
    BFP_PROJECTION_NULL = 0,
    BFP_PERSPECTIVE_TYPE,
    BFP_ORTHO_TYPE
};

enum BFP_ELEMENT_TYPE {
    BFP_ELEMENT_TYPE_NULL = 0,
    BFP_ELEMENT_TYPE_IGNORE_2F,
    BFP_ELEMENT_TYPE_IGNORE_3F,
    BFP_ELEMENT_TYPE_VERTEX_3F,
    BFP_ELEMENT_TYPE_NORMAL_3F,
    BFP_ELEMENT_TYPE_COLOR_3F,
    BFP_ELEMENT_TYPE_TEX1_2F,
    BFP_ELEMENT_TYPE_TEX2_2F,
    BFP_ELEMENT_TYPE_TEX3_2F,
    BFP_ELEMENT_TYPE_TEX4_2F,
    BFP_ELEMENT_TYPE_TEX5_2F,
    BFP_ELEMENT_TYPE_TEX6_2F,
    BFP_ELEMENT_TYPE_TEX7_2F,
    BFP_ELEMENT_TYPE_TEX8_2F,
    BFP_ELEMENT_TYPE_TEX1_3F,
    BFP_ELEMENT_TYPE_TEX2_3F,
    BFP_ELEMENT_TYPE_TEX3_3F,
    BFP_ELEMENT_TYPE_TEX4_3F,
    BFP_ELEMENT_TYPE_TEX5_3F,
    BFP_ELEMENT_TYPE_TEX6_3F,
    BFP_ELEMENT_TYPE_TEX7_3F,
    BFP_ELEMENT_TYPE_TEX8_3F
};

enum BFP_PRIMITIVE_TYPE {
    BFP_PRIMITIVE_NULL = 0,
    BFP_PRIMITIVE_POINT_LIST,
    BFP_PRIMITIVE_TRI_LIST,
    BFP_PRIMITIVE_TRI_STRIP,
    BFP_PRIMITIVE_LINE_LIST,
    BFP_PRIMITIVE_LINE_STRIP
};

enum BFP_SHADER_TYPE {
    BFP_VERTEX_SHADER = 1,
    BFP_PIXEL_SHADER
};

#define BFP_MAX_LOD         3
#define BFP_FILTER_LIST     std::vector<BFP_FILTER_TYPE>
#define BFP_FILTER_LIST_PTR BFP_FILTER_LIST*

enum BFP_OCTREE_NODE_ID
{
    TOP_FRONT_LEFT = 0,
    TOP_FRONT_RIGHT,
    TOP_BACK_LEFT,
    TOP_BACK_RIGHT,
    BOTTOM_FRONT_LEFT,
    BOTTOM_FRONT_RIGHT,
    BOTTOM_BACK_LEFT,
    BOTTOM_BACK_RIGHT
};

#define BFP_KEYBOARD_KEY_NUM   256

enum BFP_INPUT_BUTTON {
    BFP_BUTTON_LEFT_SHOULDER = 1,
    BFP_BUTTON_RIGHT_SHOULDER,
    BFP_BUTTON_LEFT_TRIGGER,
    BFP_BUTTON_RIGHT_TRIGGER,
    BFP_BUTTON_LEFT_THUMB,
    BFP_BUTTON_RIGHT_THUMB,
    BFP_BUTTON_START,
    BFP_BUTTON_BACK,
    BFP_BUTTON_ARROW_UP,
    BFP_BUTTON_ARROW_DOWN,
    BFP_BUTTON_ARROW_LEFT,
    BFP_BUTTON_ARROW_RIGHT,
    BFP_BUTTON_A,
    BFP_BUTTON_B,
    BFP_BUTTON_X,
    BFP_BUTTON_Y,
    BFP_BUTTON_MOUSE_LEFT,
    BFP_BUTTON_MOUSE_RIGHT,
    BFP_BUTTON_0,
    BFP_BUTTON_1,
    BFP_BUTTON_2,
    BFP_BUTTON_3,
    BFP_BUTTON_4,
    BFP_BUTTON_5,
    BFP_BUTTON_6,
    BFP_BUTTON_7,
    BFP_BUTTON_8,
    BFP_BUTTON_9,
    BFP_BUTTON_C,
    BFP_BUTTON_D,
    BFP_BUTTON_E,
    BFP_BUTTON_F,
    BFP_BUTTON_G,
    BFP_BUTTON_H,
    BFP_BUTTON_I,
    BFP_BUTTON_J,
    BFP_BUTTON_K,
    BFP_BUTTON_L,
    BFP_BUTTON_M,
    BFP_BUTTON_N,
    BFP_BUTTON_O,
    BFP_BUTTON_P,
    BFP_BUTTON_Q,
    BFP_BUTTON_R,
    BFP_BUTTON_S,
    BFP_BUTTON_T,
    BFP_BUTTON_U,
    BFP_BUTTON_V,
    BFP_BUTTON_W,
    BFP_BUTTON_Z,
    BFP_BUTTON_ESCAPE,
    BFP_BUTTON_SPACE,
    BFP_BUTTON_ENTER,
    BFP_TOTAL_BUTTONS
};

#define BFP_X360_DEADZONE (0.24 * FLOAT(0x7FFF))

#define BFP_X360_DEADZONE_CHECK(stickX, stickY, val) \
    if((stickX < val && stickX > -val) && \
       (stickY < val && stickY > -val)) \
    { \
        stickX = 0; \
        stickY = 0; \
    }

#endif